/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <stdio.h>
#define MAX 4000000
int main(){
	long f1=1, f2=1;
	long fcurr,sum=0;
	while(1){
		fcurr = f1 + f2;
		f1 = f2;
		f2 = fcurr;
		if(fcurr>MAX)
		break;
		if(fcurr%2==0){
			sum+=fcurr;
		}
	}
	printf("The sum = %ld", sum);
}
